source "https://rubygems.org"

gem "kitchen-ansible"
gem "kitchen-sync"
gem "kitchen-vagrant"
gem "kitchen-verifier-serverspec"
gem "kitchen-verifier-shell"
gem "rake"
gem "rspec"
gem "rspec-retry"
gem "rubocop", "~> 0.51.0"
gem "serverspec"
gem "specinfra"
gem "test-kitchen"
